-- MySQL Script generated by MySQL Workbench
-- Fri Jul 14 20:33:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema asesorias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asesorias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asesorias` DEFAULT CHARACTER SET utf8 ;
USE `asesorias` ;

-- -----------------------------------------------------
-- Table `asesorias`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesorias`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(45) NOT NULL,
  `nombreCompleto` VARCHAR(45) NOT NULL,
  `fechaNacimiento` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `comuna` VARCHAR(45) NOT NULL,
  `afp` VARCHAR(45) NULL,
  `sistemaSalud` VARCHAR(45) NULL,
  `fechaIngreso` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `area` VARCHAR(45) NULL,
  `experiencia` VARCHAR(45) NULL,
  `tipoUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asesorias`.`capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesorias`.`capacitacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(45) NULL,
  `diaCapacitacion` VARCHAR(45) NULL,
  `hora` VARCHAR(45) NULL,
  `lugar` VARCHAR(45) NULL,
  `cantidadAsistente` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asesorias`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesorias`.`contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `mensaje` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asesorias`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesorias`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
